spec/ParsePushAdapter.spec.js, src/APNS.js, src/GCM.js, src/ParsePushAdapter.js
- Better report errors
- Make sure each sender reports properly their status (deviceType and deviceToken)
=> reports all sending error for mis-configurations

README.md, package.json, src/APNS.js, src/GCM.js, src/ParsePushAdapter.js, src/index.js
Improves logging in parse-server-push adapter
enable logging with VERBOSE=1 or VERBOSE_PARSE_SERVER_PUSH_ADAPTER=1
=> Adds verbose logging

src/ParsePushAdapter.js
Added check for empty devices sets when sending push notifications to
senders. This fixes and issue where the empty sets being processed by
the senders would throw several reference errors.
Fixes  ParsePlatform/parse-server#1245
=> Fixed error when sending pushes to one pushType

spec/APNS.spec.js, src/APNS.js
parse-server expresses epoch time in milliseconds, while APNS expects it to be in seconds.
This causes parse-server (when correctly configured to send to APNS) to crash when the following cloud code is executed:
```
Parse.Cloud.define("testPush", function(request, response) {
var query = new Parse.Query(Parse.Installation);
query.equalTo( <query...> );
var today = new Date();
var timeout = new Date(today.getFullYear(), today.getMonth(), today.getDay() + 1);
Parse.Push.send({
where: query,
expiration_time: timeout,
data: {alert: "push hello"},
}, {
useMasterKey: true,
success: response.success,
error: response.error,
});
});
```
with the error:
```
verbose: sending push to 69 installations
verb parse-server-push-adapter APNS APNS Connection 0 Connected
verb parse-server-push-adapter APNS …
```
=> APNS expects expiration time to be in seconds, not MS.

spec/APNS.spec.js, src/APNS.js
=> Push notifications to APNS per batches

package.json, spec/APNS.spec.js, src/APNS.js
In iOS 10, remote notification payloads can be mutated on the client before presentation to the user, allowing for rich content to be displayed (images, video).
The key to this is a mutable-content boolean value in the payload that must be set to 1.
I have added support for mutable-content, along with a test, and updated the `apn` dependency.
Further information in the WWDC presentation (page 16): http://devstreaming.apple.com/videos/wwdc/2016/708tbh8wnspsg01hxwx/708/708_advanced_notifications.pdf
=> Support `mutable-content`

spec/ParsePushAdapter.spec.js, src/PushAdapterUtils.js
I wrote an adapter that basically extend the ParsePushAdapter, keeping the overall logic, and added custom *Firebase Cloud Messaging* driver.  From what I read from the documents it should be pushType, not deviceType, that will determine which sender should be adpted.
=> Classify installation with pushType and failback with deviceType

spec/ParsePushAdapter.spec.js, src/PushAdapterUtils.js
Since FCM works for both Apple and Android devices, we need to have **deviceType** provided for the push handler to report status by device type
=> Send deviceType key to push handler

spec/GCM.spec.js, spec/ParsePushAdapter.spec.js, src/GCM.js, src/ParsePushAdapter.js
Related to #32.  
You should be able to send notifications this way:
```
POST /api/push HTTP/1.1
Host: localhost:1337
X-Parse-Application-Id: TEST_APP_ID
X-Parse-Master-Key: TEST_MASTER_KEY
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 277e9e75-565d-1a81-b80b-1575809fbac6
{
"where": {
"objectId" : "yTgONHk2il"
},
"data": {
"data" : "Hello World!"
},
"notification": {
"title": "I am a title",
"body": "I am the body"
}
}
```  
Why do you need a notification field?
Because with the recent gcm -> fcm migration the notification field is required for showing the notification when the app is in background.
```javascript
// push adapter config
push: {
fcm: {
senderId: keys.FCM_SENDER_ID,
apiKey: keys.FCM_API_KEY
}
}
```
From my testing it works on both Android and iOS.
=> Added notification field for fcm [WIP]

src/GCM.js
new Array(...devices); expands to include apply(,args) which is limited.
=> fixes 64k limit on GCM push.

README.md
The old parse server push configuration link https://github.com/ParsePlatform/parse-server/wiki/Push is broken. New link for the guide is here: http://parseplatform.github.io/docs/parse-server/guide/#push-notifications
=> Fixed link for Parse-server push configuration

src/ParsePushAdapter.js
This is just a tiny little fix. The error message should print the unsupported push type instead of the array of supported push types.
=> fix error message

spec/APNS.spec.js, src/APNS.js
Added support for adding `apns-collapse-id` to enable collapsing of pushes just like the `apns-expiration`.
I changed the method signature for `APNS_generateNotification` from `APNS._generateNotification(data, expirationDate)` to `APNS._generateNotification(data, headers)` making it easier to add more header properties in the future.
The headers parameter is a JS object with the following supported properties:
- expirationTime
- collapseID
- topic
Don't hesitate to feedback on the code as JS isn't my "native" language :)
=> Add support for passing collapse-id to APNS

src/APNS.js
As of iOS 8.2 Apple added the ability to send a "title" attribute with notifications.
APNS notification can now look like this:
{   
"aps": {
"alert": {
"title": "notification_title",
"body": "notification_content"
}
},
User-defined key-value pairs
}
Therefore sending a title attribute with Parse-Push on iOS need to be added within the "alert" statement and not the "User-defined key-value pairs" to be properly displayed by iOS devices.
=> Update APNS.js - Add iOS Notification Title

spec/APNS.spec.js, src/APNS.js
This change ensures that the dashboard will support the following JSON payload:
```
{
"aps" : {
"alert" : {
"title" : "Game Request",
"body" : "Bob wants to play poker",
"action-loc-key" : "PLAY"
},
"badge" : 5
},
"acme1" : "bar",
"acme2" : [ "bang",  "whiz" ]
}
```
or this one:
```
{
"aps" : {
"alert" : {
"loc-key" : "GAME_PLAY_REQUEST_FORMAT",
"loc-args" : [ "Jenna", "Frank"]
},
"sound" : "chime.aiff"
},
"acme" : "foo"
}
```
This is a more advanced way of sending aps data, sure, but this ensures that current and future unsupported keys will continue to work.
=> Ensured that raw aps data is correctly parsed

spec/APNS.spec.js, src/APNS.js
This pull request quickly addresses the issue where ``apns-expiration`` header that gets sent to the Apple Push Notification Service gets wrongly computed into a floating point number thus generating push error 400 BadExpirationDate reported here https://github.com/parse-community/parse-server/issues/4558.
I have tested in production that this fix gets rid of the error and pushes are going through.
I have not tested or reviewed the logic of computing correct push expiration date from push date.
=> make sure we always send apns-expiration as integer number 

spec/APNS.spec.js
Should be set to 10 if not defined explicitly.
From Apple docs:
> The priority of the notification. If you omit this header, APNs sets the notification priority to 10.
> Specify 10 to send the notification immediately. A value of 10 is appropriate for notifications that trigger an alert, play a sound, or badge the app’s icon. It's an error to specify this priority for a notification whose payload contains the content-available key.
> Specify 5 to send the notification based on power considerations on the user’s device. Use this priority for notifications whose payload includes the content-available key. Notifications with this priority might be grouped and delivered in bursts to the user’s device. They may also be throttled, and in some cases not delivered.
=> Add test case for apns priority

package-lock.json, package.json, spec/APNS.spec.js, src/APNS.js
**Required when delivering notifications to devices running iOS 13 and later, or watchOS 6 and later.**
Apple docs: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
I opened a PR on `node-apn` to support this key. Support from `node-apn` is required to make this PR work.
PR: https://github.com/node-apn/node-apn/pull/656
=> Add support for apns-push-type

spec/APNS.spec.js, src/APNS.js
https://docs.parseplatform.org/js/guide/#customizing-your-notifications
The docs says that the headers should be in the data field
=> Support headers in data field

src/GCM.js
I noticed that it is not possible to send notifications to iOS devices due to not being able to pass the correct option to node-gcm. I fixed this wrong string. I tested it, it works great. For typescript the types need to be updated I'll also do it as soon as this is merged
This fixes #164 
https://github.com/ToothlessGear/node-gcm
=> Fixed wrong usage of contentAvailable for iOS push notifications via Firebase

package-lock.json, package.json, spec/APNS.spec.js, src/APNS.js
This PR along with https://github.com/parse-community/node-apn/pull/87 adds support for specification of `target-content-id` and `interruption-level` in APNS push notification payload to address https://github.com/parse-community/parse-server-push-adapter/issues/196 and https://github.com/parse-community/parse-server-push-adapter/issues/155.
=> feat: add support for APNS `interruption-level` and `target-content-id`

.github/workflows/ci.yml
Ubuntu version is outdated.
Related issue: #n/a
Set ubuntu to `latest`.
=> ci: Fix CI not running due to outdated ubuntu version

.github/workflows/ci.yml
CI tests only against Node 14.
Related issue: #n/a
Add Node version matrix to CI to test against multiple Node versions.
=> ci: Add Node versions to test

package-lock.json, package.json
Various dependencies are outdated.
Related issue: #n/a
- Upgrade to node-apm 6.0.1, parse 4.2.0
- BREAKING CHANGE: removes support for Node 12.
=> feat: Upgrade to node-apn 6.0.1, parse 4.2.0

package-lock.json, package.json, src/FCM.js, src/ParsePushAdapter.js
Closes https://github.com/parse-community/parse-server-push-adapter/issues/219.
Adds FCM support to the parse-server-push-adapter.
- Mostly re-uses the structure from GCM.js.
- Currently makes all deviceTypes use FCM. Not sure if this is what we want.
- Tested on both iOS and Android (flutter). 
- Requires the user to specify the exact payload they want. 
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
Payload example:
```javascript
await Parse.Push.send(
{
where: query,
notification: {
title: title,
body: body
},
data: {
type: type
},
android: {
priority: 'high'
},
apns: {
headers: {
'apns-priority': '5'
},
payload: {
aps: {
contentAvailable: true
}
}
}
},
{ useMasterKey: true }
)
```
=> feat: Send Android push notifications to Firebase Cloud Messaging API (HTTP v1) by setting the push adapter option `firebaseServiceAccount`

spec/FCM.spec.js, spec/ParsePushAdapter.spec.js, spec/support/fakeServiceAccount.json, src/FCM.js, src/ParsePushAdapter.js
As discussed in #219, we want to remain backwards compatible with both APNS and GCM payloads. For a more seamless transition for developers. A user can also specify a "raw payload" according to https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages which will be used "as-is" when sent without any payload conversion.
- Looked at the code for APNS and GCM around how payloads are generated.
- Wrote test specs to ensure that payloads are converted from GCM/APNS to a compatible FCMv1 payload. The input payload used in each test spec match the ones used in GCM.spec.js and APNS.spec.js.
In current master branch, the GCM to FCMv1 payload conversion uses the FCM "notification"[^1] and "data"[^2] key.
This was changed to use the "android" [^3] version of this since what we're …
=> feat: Add backwards compatibility with APNS payloads when using Firebase Cloud Messaging API (HTTP v1)

README.md, package-lock.json, package.json, spec/EXPO.spec.js, spec/ParsePushAdapter.spec.js, src/EXPO.js, src/ParsePushAdapter.js, src/index.js
Expo for React Native is used heavily when creating mobile app. It comes with its own simplified way to create, manage and send push notifications. 
https://docs.expo.dev/push-notifications/overview/
With the addition of Installations for Parse JS, it is now easier/possible to use the Parse Server send push notifications using internals
=> feat: Add support for Expo push notifications

README.md
Small rewriting of the README for better docs.
Related issue: n/a
=> docs: Fix readme style

README.md
=> docs: Restyle readme

.releaserc.js
Fixes auto-releases and enables it.
=> ci: Fix auto-release

README.md, package-lock.json, package.json, spec/FCM.spec.js, src/FCM.js
firebase-admin recently added support to this in the release of [v12.3.0](https://github.com/firebase/firebase-admin-node/releases/tag/v12.3.0).
Closes: #251 
- Bump version to v12.3.0. 
- Provide new flag in push options for FCM to enable legacy HTTP transport if wanted.
Tested and working.
=> feat: Add Firebase Cloud Messaging (FCM) HTTP/2 support and option `fcmEnableLegacyHttpTransport` to use legacy HTTP/1.1

.gitignore, README.md, spec/.eslintrc.json, spec/FCM.spec.js, src/FCM.js
Closes: #340 
- Wrap push sending into try/catch block as firebase-admin client throws instead of rejecting promise.
- Add new FCM option `resolveUnhandledClientError` that allows to customize whether client errors should be gracefully resolved (set to `true`), or lead to a promise rejection for the caller to indicate that sending the push failed (set to `false`). Default is `false`.
=> feat: Add FCM option `resolveUnhandledClientError` to resolve or reject push promise on FCM server response GOAWAY

spec/APNS.spec.js, src/APNS.js
An APN notification `topic` currently stays as the `topic` initialized by the Parse-Server (`_Installation.appIdentifier`) and isn't updated based on `pushType`. Based on the [Apple Documentation](https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns#Know-when-to-use-push-types), a specific `pushType` may require a `topic` to change.  
In addition, the notification header determined by `parse-server-push-adapter` currently has the highest priority. This makes it harder for the developer to specify particular header information in Cloud Code to prioritize over `parse-server-push-adapter` header information (parse-server running in memory). This is also useful when Apple updates/adds new notification types and allows devs to add updates to their …
=> fix: APN notification topic not composed based on push type

.github/workflows/ci.yml
Related issue: #`FILL_THIS_OUT`
=> ci: Fix code coverage reporting

.github/workflows/ci.yml, README.md, spec/ParsePushAdapter.spec.js, src/ParsePushAdapter.js
Closes: #361 
Similar approach to #58
=> feat: Add support for watchOS push notifications
